CONFIG_CPP=y
CONFIG_STD_CPP17=y

#enable app log
CONFIG_APP_LOG=y

#enable battery conttroller and logs
CONFIG_BATTERY_LEVEL_DRV=y
CONFIG_BATTERY_LEVEL_LOG=y

#enable motor conttroller and logs
CONFIG_MOTOR_CONTROLLER_DRV=y
CONFIG_MOTOR_CONTROLLER_LOG=y

#enable interface controller and logs
CONFIG_INTERFACE_DRV=y
CONFIG_INTERFACE_LOG=y

#enable logs from utlis module
CONFIG_UTLIS_LOG=y

#enable logger driver
CONFIG_LOGGER_DRV=y
CONFIG_LOG_OVER_BLE=y
CONFIG_LOG_OVER_SERIAL=y

