CONFIG_CPP=y
CONFIG_STD_CPP17=y

#Enable battery level measurement
CONFIG_BATTERY_LEVEL_DRV=y

# Enable IMU driver and related modules:
CONFIG_IMU_DRV=y
CONFIG_MPU6050=y
CONFIG_MPU6050_TRIGGER_GLOBAL_THREAD=y
CONFIG_GPIO=y # To be checked if it's needed
CONFIG_SENSOR=y
CONFIG_I2C=y