CONFIG_CPP=y
CONFIG_STD_CPP17=y

# Enable battery controller and logs:
CONFIG_BATTERY_LEVEL_DRV=y
CONFIG_BATTERY_LEVEL_LOG=y

# Enable motor controller and logs:
CONFIG_MOTOR_CONTROLLER_DRV=y
CONFIG_MOTOR_CONTROLLER_LOG=y

# Enable interface controller and logs:
CONFIG_INTERFACE_DRV=y
CONFIG_INTERFACE_LOG=y

# Enable IMU driver, related modules and logs:
CONFIG_IMU_DRV=y
CONFIG_IMU_LOG=y

# Enable balance regulator and logs:
CONFIG_REGULATOR_DRV=y
CONFIG_REGULATOR_LOG=y

# Enable logs from utils module:
CONFIG_UTILS_LOG=y

# Enable logger driver:
CONFIG_LOGGER_DRV=y
CONFIG_LOG_OVER_SERIAL=y
CONFIG_LOG_OVER_BLE=y

# Enable app log:
CONFIG_APP_LOG=n

# Enable debug:
CONFIG_APP_DEBUG=y

# Enable FPU module for proper floats handling:
CONFIG_FPU=y