if(DEFINED CONFIG_BATTERY_LEVEL_DRV OR DEFINED CONFIG_INTERFACE_DRV OR DEFINED CONFIG_REGULATOR_DRV)
    add_subdirectory(utils)
endif()

add_subdirectory_ifdef(CONFIG_BATTERY_LEVEL_DRV battery_level)
add_subdirectory_ifdef(CONFIG_MOTOR_CONTROLLER_DRV motor_controller)
add_subdirectory_ifdef(CONFIG_IMU_DRV imu)
add_subdirectory_ifdef(CONFIG_LOGGER_DRV logger)
add_subdirectory_ifdef(CONFIG_INTERFACE_DRV interface)
add_subdirectory_ifdef(CONFIG_REGULATOR_DRV regulator)
add_subdirectory_ifdef(CONFIG_MODEL_IDENTIFICATION_DRV model_identification)
