CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# Enable battery controller and logs:
CONFIG_BATTERY_LEVEL_DRV=y
CONFIG_BATTERY_LEVEL_LOG=n

# Enable motor controller and logs:
CONFIG_MOTOR_CONTROLLER_DRV=y
CONFIG_MOTOR_CONTROLLER_LOG=n

# Enable interface controller and logs:
CONFIG_INTERFACE_DRV=y
CONFIG_INTERFACE_LOG=n

# Enable IMU driver, related modules and logs:
CONFIG_IMU_DRV=y
CONFIG_IMU_LOG=y

# Enable balance regulator and logs:
CONFIG_ROBOT_CONTROL=y
CONFIG_ROBOT_CONTROL_LOG=n

# Balance controller selection: PID - y, LQR - n:
CONFIG_PID_ENABLED=y

# Enable model identification driver and logs:
CONFIG_MODEL_IDENTIFICATION_DRV=n
CONFIG_MODEL_IDENTIFICATION_LOG=n

# Enable logs from utils module:
CONFIG_UTILS_LOG=n

# Enable logger drivers:
CONFIG_LOGGER_DRV=y
CONFIG_LOG_OVER_SERIAL=y
CONFIG_LOG_OVER_BLE=y

# Enable app log:
CONFIG_APP_LOG=y

# Enable debug:
CONFIG_APP_DEBUG=y

# Enable FPU module for proper floats handling:
CONFIG_FPU=y

# ±4g for accelerometer:
CONFIG_MPU6050_ACCEL_FS=2

# ±500°/s for gyro: 
CONFIG_MPU6050_GYRO_FS=250

CONFIG_ENCODER_DRV=y

CONFIG_REBOOT=y
